<?php
require_once __DIR__ . '/../includes/functions.php';
require_admin();
$stats=ReportService::dashboardStats(); $recent=ReportService::recentOrders(8); $low=Product::lowStock((int)setting('low_stock_threshold','5')); $sales=ReportService::salesByPeriod('monthly'); $activity=ReportService::activity(8);
$pageTitle='Admin Dashboard'; $activePage='dashboard'; require __DIR__.'/../includes/header.php';
?>
<main class="container-fluid admin-shell"><div class="row g-4"><aside class="col-lg-2"><?php require __DIR__.'/../includes/sidebar.php'; ?></aside><section class="col-lg-10"><h1 class="section-title mb-4">Admin Dashboard</h1><div class="row g-3 mb-4">
<?php $cards=[['Products',$stats['products'],'bi-box-seam'],['Categories',$stats['categories'],'bi-tags'],['Customers',$stats['customers'],'bi-people'],['Orders',$stats['orders'],'bi-receipt'],['Revenue',money($stats['revenue']),'bi-currency-dollar']]; foreach($cards as $card): ?><div class="col-md-6 col-xl"><div class="card dashboard-card p-3"><div class="d-flex gap-3 align-items-center"><div class="icon"><i class="bi <?= e($card[2]) ?>"></i></div><div><small class="text-muted"><?= e($card[0]) ?></small><h4 class="mb-0"><?= e((string)$card[1]) ?></h4></div></div></div></div><?php endforeach; ?></div>
<div class="row g-4"><div class="col-xl-7"><div class="card table-card p-3"><h5 class="fw-bold">Revenue Analytics</h5><canvas id="revenueChart" height="120"></canvas></div></div><div class="col-xl-5"><div class="card table-card"><div class="card-header bg-white fw-bold">Low Stock Alert</div><div class="table-responsive"><table class="table mb-0"><thead class="table-light"><tr><th>Product</th><th>Stock</th></tr></thead><tbody><?php foreach(array_slice($low,0,6) as $p): ?><tr><td><?= e($p['product_name']) ?></td><td><span class="badge bg-danger"><?= (int)$p['stock_quantity'] ?></span></td></tr><?php endforeach; if(!$low): ?><tr><td colspan="2" class="text-center text-muted py-3">No low stock products.</td></tr><?php endif; ?></tbody></table></div></div></div></div>
<div class="row g-4 mt-1"><div class="col-xl-7"><div class="card table-card"><div class="card-header bg-white fw-bold">Recent Orders</div><div class="table-responsive"><table class="table mb-0 align-middle"><thead class="table-light"><tr><th>Order</th><th>Customer</th><th>Total</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($recent as $o): ?><tr><td>#<?= (int)$o['id'] ?></td><td><?= e($o['customer_name']) ?></td><td><?= money($o['total_amount']) ?></td><td><?= order_status_badge($o['order_status']) ?></td><td><a class="btn btn-sm btn-outline-primary" href="<?= url('admin/manage_orders.php?order_id='.(int)$o['id']) ?>">View</a></td></tr><?php endforeach; ?></tbody></table></div></div></div><div class="col-xl-5"><div class="card table-card"><div class="card-header bg-white fw-bold">Recent Activity Logs</div><div class="list-group list-group-flush"><?php foreach($activity as $a): ?><div class="list-group-item"><span class="activity-dot me-2"></span><?= e($a['message']) ?><br><small class="text-muted"><?= e(date('d M Y h:i A',strtotime($a['created_at']))) ?></small></div><?php endforeach; if(!$activity): ?><div class="p-4 text-muted text-center">No activity yet.</div><?php endif; ?></div></div></div></div>
</section></div></main>
<script>window.addEventListener('DOMContentLoaded',()=>{const el=document.getElementById('revenueChart');if(el&&window.Chart){new Chart(el,{type:'line',data:{labels:<?= json_encode(array_column($sales,'label')) ?>,datasets:[{label:'Revenue',data:<?= json_encode(array_map('floatval',array_column($sales,'revenue'))) ?>,tension:.35}]},options:{plugins:{legend:{display:false}},scales:{y:{beginAtZero:true}}}});}});</script>
<?php require __DIR__.'/../includes/footer.php'; ?>
