<?php
require_once __DIR__ . '/../includes/functions.php';
require_admin();
$id=(int)($_GET['id'] ?? 0); $product=Product::find($id); if(!$product){ set_flash('danger','Product not found.'); redirect('admin/manage_products.php'); }
if($_SERVER['REQUEST_METHOD']==='POST'){ require_post_csrf(); try{ Product::update($id,$_POST,$_FILES['image'] ?? []); set_flash('success','Product updated.'); redirect('admin/manage_products.php'); }catch(Throwable $e){ set_flash('danger',$e->getMessage()); } $product=Product::find($id); }
$categories=Category::all(); $pageTitle='Edit Product'; $activePage='products'; require __DIR__.'/../includes/header.php';
?>
<main class="container-fluid admin-shell"><div class="row g-4"><aside class="col-lg-2"><?php require __DIR__.'/../includes/sidebar.php'; ?></aside><section class="col-lg-10"><h1 class="section-title mb-4">Edit Product</h1><div class="card form-card"><div class="card-body p-4"><form method="post" enctype="multipart/form-data"><?= csrf_input() ?><div class="row g-3"><div class="col-md-6"><label class="form-label">Product Name</label><input name="product_name" class="form-control" required value="<?= e($product['product_name']) ?>"></div><div class="col-md-6"><label class="form-label">Category</label><select name="category_id" class="form-select" required><?php foreach($categories as $cat): ?><option value="<?= (int)$cat['id'] ?>" <?= (int)$product['category_id']===(int)$cat['id']?'selected':'' ?>><?= e($cat['category_name']) ?></option><?php endforeach; ?></select></div><div class="col-md-4"><label class="form-label">Price</label><input type="number" step="0.01" min="0" name="price" class="form-control" required value="<?= e($product['price']) ?>"></div><div class="col-md-4"><label class="form-label">Discount Price</label><input type="number" step="0.01" min="0" name="discount_price" class="form-control" value="<?= e($product['discount_price']) ?>"></div><div class="col-md-4"><label class="form-label">Stock Quantity</label><input type="number" min="0" name="stock_quantity" class="form-control" required value="<?= (int)$product['stock_quantity'] ?>"></div><div class="col-md-6"><label class="form-label">Replace Image</label><input type="file" name="image" accept="image/jpeg,image/png,image/webp" class="form-control"><?php if($product['image']): ?><img class="cart-thumb mt-2" src="<?= e(product_image_url($product['image'])) ?>"><?php endif; ?></div><div class="col-md-6"><label class="form-label">Status</label><select name="status" class="form-select"><option value="active" <?= $product['status']==='active'?'selected':'' ?>>Active</option><option value="inactive" <?= $product['status']==='inactive'?'selected':'' ?>>Inactive</option></select></div><div class="col-12"><label class="form-label">Description</label><textarea name="description" rows="5" class="form-control" required><?= e($product['description']) ?></textarea></div></div><button class="btn btn-primary mt-4">Update Product</button></form></div></div></section></div></main>
<?php require __DIR__.'/../includes/footer.php'; ?>
