<?php
require_once __DIR__ . '/../includes/functions.php';
require_customer();
$customerId=(int)$_SESSION['customer_id'];
$action=$_GET['action'] ?? '';
if ($_SERVER['REQUEST_METHOD']==='POST' && $action) { require_post_csrf(); $productId=(int)($_POST['product_id'] ?? 0); try { if($action==='add'){ Wishlist::add($customerId,$productId); set_flash('success','Added to wishlist.'); } elseif($action==='remove'){ Wishlist::remove($customerId,$productId); set_flash('success','Removed from wishlist.'); } elseif($action==='move'){ Cart::add($customerId,$productId,1); Wishlist::remove($customerId,$productId); set_flash('success','Moved to cart.'); } } catch(Throwable $e){ set_flash('danger',$e->getMessage()); } header('Location: '.safe_back_url('customer/wishlist.php')); exit; }
$items=Wishlist::items($customerId); $pageTitle='Wishlist'; $activePage='wishlist'; require __DIR__.'/../includes/header.php';
?>
<main class="container account-shell"><div class="row g-4"><aside class="col-lg-3"><?php require __DIR__.'/../includes/sidebar.php'; ?></aside><section class="col-lg-9"><h1 class="section-title mb-4">Wishlist</h1><?php if(!$items): ?><div class="empty-state"><i class="bi bi-heart fs-1 d-block mb-2"></i>No wishlist products.</div><?php else: ?><div class="row g-4"><?php foreach($items as $item): ?><div class="col-md-6"><div class="card product-card h-100"><img src="<?= e(product_image_url($item['image'])) ?>" class="card-img-top" style="height:220px;object-fit:cover"><div class="card-body"><h5><?= e($item['product_name']) ?></h5><p class="fw-bold text-primary"><?= money((float)($item['discount_price'] ?? $item['price'])) ?></p><div class="d-flex gap-2"><form method="post" action="<?= url('customer/wishlist.php?action=move') ?>"><?= csrf_input() ?><input type="hidden" name="product_id" value="<?= (int)$item['product_id'] ?>"><button class="btn btn-primary btn-sm" <?= (int)$item['stock_quantity']<=0?'disabled':'' ?>>Move to Cart</button></form><form method="post" action="<?= url('customer/wishlist.php?action=remove') ?>" class="confirm-form no-loader"><?= csrf_input() ?><input type="hidden" name="product_id" value="<?= (int)$item['product_id'] ?>"><button class="btn btn-outline-danger btn-sm">Remove</button></form></div></div></div></div><?php endforeach; ?></div><?php endif; ?></section></div></main>
<?php require __DIR__.'/../includes/footer.php'; ?>
